---
title: "pittsburgh_zoning"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)
```

```{r}
library(tidyverse)
library(sf)
library(ggmap)
library(janitor)

options(scipen = 999)
```

```{r}
shapefile <- st_read("data/Zoning.shp")

glimpse(shapefile)
```

```{r}
df <- shapefile %>% 
  mutate(residential = str_detect(full_zonin, "RESIDENT"),
         single_unit = str_detect(full_zonin, "SINGLE-UNIT"),
         attached = str_detect(full_zonin, "ATTACHED"),
         type = case_when(residential == TRUE & single_unit == TRUE & attached == FALSE ~ "Single-unit detached residential",
                          residential == TRUE & single_unit == FALSE | attached == TRUE ~ "Other residential",
                          full_zonin == "EDUCATIONAL/MEDICAL INSTITUTION" ~ "Educational/Medical",
                          residential == FALSE ~ "Other non-residential"),
         type = factor(type, levels = c("Single-unit detached residential", 
                                        "Other residential",
                                        "Educational/Medical",
                                        "Other non-residential")),
         alpha_flag = type == "Single-unit detached residential")
df
```

```{r}
df_zones <- df %>% 
  count(full_zonin, type, sort = TRUE) %>% 
  st_drop_geometry()
df_zones
```

```{r}
df %>% 
  st_drop_geometry() %>% 
  group_by(type, residential) %>% 
  summarize(area = sum(area)) %>% 
  #arrange(residential, desc(area)) %>% 
  ungroup() %>% 
  mutate(type = fct_reorder(type, area)) %>% 
  ggplot(aes(type, area, fill = residential)) +
  geom_col() +
  #facet_wrap(~residential, scale = "free_y") +
  coord_flip() +
  theme_bw()
```

```{r}
df %>% 
  st_drop_geometry() %>% 
  group_by(full_zonin, residential) %>% 
  summarize(area = sum(area)) %>% 
  #arrange(residential, desc(area)) %>% 
  ungroup() %>% 
  mutate(full_zonin = fct_reorder(full_zonin, area)) %>% 
  ggplot(aes(full_zonin, area, fill = residential)) +
  geom_col() +
  #facet_wrap(~residential, scale = "free_y") +
  coord_flip() +
  theme_bw()
```

```{r}
df %>% 
  st_drop_geometry() %>% 
  mutate(single_unit_flag = type == "Single-unit detached residential") %>% 
  filter(residential == TRUE) %>% 
  summarize(total_area = sum(area))
```

```{r}
df %>% 
  st_drop_geometry() %>% 
  filter(residential == TRUE) %>% 
  mutate(single_unit_flag = (type == "Single-unit detached residential")) %>% 
  group_by(single_unit_flag) %>% 
  summarize(zone_area = sum(area)) %>% 
  mutate(pct_area = zone_area / sum(zone_area))
```
  
```{r}
zone_map <- df %>% 
  ggplot(aes(fill = type)) +
    geom_sf(size = .5) +
    scale_fill_manual("Zone type",
                      values = c("#ea60b9", "#4cafc5", "yellow", "light grey")) +
    labs(title = "56% of residential zoned land area is single-family detached residential",
         subtitle = "City of Pittsburgh zoning",
         caption = "@conor_tompkins, data from WPRDC") +
    theme_void()
zone_map
```

#overlay on google map

```{r}
register_google(key = "your key here")
pgh_map <- get_map(location = "The Hill, Pittsburgh, PA", zoom = 12)

ggmap(pgh_map) +
  geom_sf(data = df, aes(fill = type), inherit.aes = FALSE, size = .5, alpha = .5) +
  coord_sf(crs = st_crs(4326)) +
  scale_fill_manual("Zone type",
                      values = c("#ea60b9", "#4cafc5", "yellow", "light grey")) +
  labs(title = "56% of residential zoned land area is single-family detached residential",
         subtitle = "City of Pittsburgh zoning",
         caption = "@conor_tompkins, data from WPRDC") +
  theme_void()
```


  